### ISSUE TITLE
[Translation] 日本語 日本 ja_JP

### ISSUE THREAD

**Issue by JanMaki** [dscalzi/SkyChanger#2]
Hi. i'm janmaki.

I translated it into Japanese.

File :
 https://dl.dropbox.com/s/qorxlxsqpzz7rv1/Messages_ja_JP.properties

**Comment by dscalzi** [comment]
Thanks for this. I probably won't release it for at least a week. If you want to use it sooner you can get the dev build from here https://ci.appveyor.com/project/dscalzi/skychanger/build/artifacts

**Comment by dscalzi** [comment]
Hey @JanMaki, could you translate the following for me? Thanks.

```
This feature is not supported on version(s): {0}.
```

**Comment by JanMaki** [comment]
> Hey @JanMaki, could you translate the following for me? Thanks.
> 
> ```
> This feature is not supported on version(s): {0}.
> ```
OK. This is Japanese

この機能はこのバージョンでサポートされていません： {0}
