### ISSUE TITLE
Can't import in Maven

### ISSUE THREAD

**Issue by M4cs** [dscalzi/SkyChanger#7]
For some reason IntelliJ can't find the Artifact for 3.1.1 on the repository you provided. Is it hosted somewhere else?

**Comment by dscalzi** [comment]
Hey, the artifact is on jcenter, you can see that here. https://jcenter.bintray.com/com/dscalzi/.

In the readme I see that I have a http link, I believe they are https only now. Try changing that.

**Comment by M4cs** [comment]
This worked! Thanks for an easy to use API and cool plugin. Got what I was looking to get done in under 30 minutes thanks to it! (Temp solution was just link with a system scope of the External Jar but the HTTPS seemed to fix it!)
