### ISSUE TITLE
BStats Error When Trying To Compile with Maven

### ISSUE THREAD

**Issue by M4cs** [dscalzi/SkyChanger#8]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/34947910/77032959-5029cf80-697c-11ea-8fe9-a836d243e5b0.png">

It seems you need to shade bStats or something into the release for Maven. For some reason it's unable to package with it due to the dependency for bStats.

**Comment by dscalzi** [comment]
you're missing bstat's repository - you can find that on their site
